<!DOCTYPE html>
<html>
<head>
    <title>Transaction Report</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; }
        h1 { text-align: center; color: #333; margin-bottom: 10px; }
        .header-info { text-align: center; margin-bottom: 20px; font-size: 11px; color: #666; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background-color: #4F46E5; color: white; padding: 8px; text-align: left; font-size: 11px; }
        td { border: 1px solid #ddd; padding: 6px; font-size: 10px; }
        tr:nth-child(even) { background-color: #f9f9f9; }
        .stock-in { color: green; font-weight: bold; }
        .stock-out { color: red; font-weight: bold; }
        .summary { margin-top: 20px; padding: 15px; background-color: #f0f0f0; border-radius: 5px; }
        .summary-item { display: inline-block; margin-right: 30px; }
        .footer { margin-top: 30px; text-align: center; font-size: 10px; color: #666; border-top: 1px solid #ddd; padding-top: 10px; }
    </style>
</head>
<body>
    <h1>Transaction Report</h1>
    <div class="header-info">
        <p>Generated on: {{ now()->format('F d, Y H:i:s') }}</p>
        @if(request('date_from') || request('date_to'))
        <p>Period: {{ request('date_from') ? \Carbon\Carbon::parse(request('date_from'))->format('M d, Y') : 'Start' }} - 
           {{ request('date_to') ? \Carbon\Carbon::parse(request('date_to'))->format('M d, Y') : 'End' }}</p>
        @endif
    </div>

    <div class="summary">
        <div class="summary-item">
            <strong>Total Transactions:</strong> {{ $transactions->count() }}
        </div>
        <div class="summary-item">
            <strong>Stock In:</strong> <span class="stock-in">{{ $transactions->where('type', 'in')->sum('quantity') }}</span>
        </div>
        <div class="summary-item">
            <strong>Stock Out:</strong> <span class="stock-out">{{ $transactions->where('type', 'out')->sum('quantity') }}</span>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Transaction #</th>
                <th>Date</th>
                <th>Item</th>
                <th>Type</th>
                <th>Qty</th>
                <th>Previous</th>
                <th>New Stock</th>
                <th>User</th>
            </tr>
        </thead>
        <tbody>
            @foreach($transactions as $transaction)
            <tr>
                <td>{{ $transaction->transaction_number }}</td>
                <td>{{ $transaction->transaction_date->format('M d, Y H:i') }}</td>
                <td>{{ $transaction->item->name }}<br><small>{{ $transaction->item->sku }}</small></td>
                <td class="{{ $transaction->type == 'in' ? 'stock-in' : 'stock-out' }}">
                    {{ strtoupper($transaction->type) }}
                </td>
                <td style="font-weight: bold;">{{ $transaction->quantity }}</td>
                <td>{{ $transaction->previous_stock }}</td>
                <td style="font-weight: bold;">{{ $transaction->new_stock }}</td>
                <td>{{ $transaction->user->name }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Inventory Management System - Generated by {{ auth()->user()->name }}</p>
        <p>This is a computer-generated document. No signature is required.</p>
    </div>
</body>
</html>